//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageProcessingApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Explorer application demonstrates some of the image editing capabilities and performance of the Lumia Imaging SDK by allowing you to apply a number of filter layers to existing or newly captured photos..
        /// </summary>
        public static string AboutPage_TextBlock_About {
            get {
                return ResourceManager.GetString("AboutPage_TextBlock_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Explorer version {0}.
        /// </summary>
        public static string AboutPage_TextBlock_Version {
            get {
                return ResourceManager.GetString("AboutPage_TextBlock_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string App_Menu_About {
            get {
                return ResourceManager.GetString("App_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image failed.
        /// </summary>
        public static string App_MessageBox_SaveFailed_Caption {
            get {
                return ResourceManager.GetString("App_MessageBox_SaveFailed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately saving the image failed. Would you mind trying again?.
        /// </summary>
        public static string App_MessageBox_SaveFailed_Message {
            get {
                return ResourceManager.GetString("App_MessageBox_SaveFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image type.
        /// </summary>
        public static string App_MessageBox_UnsupportedImage_Caption {
            get {
                return ResourceManager.GetString("App_MessageBox_UnsupportedImage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the type of the image you selected is unsupported by this application..
        /// </summary>
        public static string App_MessageBox_UnsupportedImage_Message {
            get {
                return ResourceManager.GetString("App_MessageBox_UnsupportedImage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTER EXPLORER.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick filter.
        /// </summary>
        public static string FilterPage_Title {
            get {
                return ResourceManager.GetString("FilterPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artistic.
        /// </summary>
        public static string FiltersPage_PivotItemHeader_Artistic {
            get {
                return ResourceManager.GetString("FiltersPage_PivotItemHeader_Artistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enhancement.
        /// </summary>
        public static string FiltersPage_PivotItemHeader_Enhancement {
            get {
                return ResourceManager.GetString("FiltersPage_PivotItemHeader_Enhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add filter.
        /// </summary>
        public static string PhotoPage_Button_AddFilter {
            get {
                return ResourceManager.GetString("PhotoPage_Button_AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save photo.
        /// </summary>
        public static string PhotoPage_Button_Save {
            get {
                return ResourceManager.GetString("PhotoPage_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share photo.
        /// </summary>
        public static string PhotoPage_Button_Share {
            get {
                return ResourceManager.GetString("PhotoPage_Button_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo filter.
        /// </summary>
        public static string PhotoPage_Button_UndoFilter {
            get {
                return ResourceManager.GetString("PhotoPage_Button_UndoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture new photo with camera.
        /// </summary>
        public static string PhotoPage_Menu_Camera {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open new photo from library.
        /// </summary>
        public static string PhotoPage_Menu_Library {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard current image?.
        /// </summary>
        public static string PhotoPage_MessageBox_Discard_Caption {
            get {
                return ResourceManager.GetString("PhotoPage_MessageBox_Discard_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current image has not been saved. Do you wish to discard the applied filters?
        ///
        ///Press ok to discard changes and go back to the camera roll stream. Press cancel to continue working with the current image..
        /// </summary>
        public static string PhotoPage_MessageBox_Discard_Message {
            get {
                return ResourceManager.GetString("PhotoPage_MessageBox_Discard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLIED FILTERS.
        /// </summary>
        public static string PhotoPage_TextBlock_Filters {
            get {
                return ResourceManager.GetString("PhotoPage_TextBlock_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PhotoPage_TextBlock_NoFilters {
            get {
                return ResourceManager.GetString("PhotoPage_TextBlock_NoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string PhotoPage_Title {
            get {
                return ResourceManager.GetString("PhotoPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture photo.
        /// </summary>
        public static string StreamPage_Button_Camera {
            get {
                return ResourceManager.GetString("StreamPage_Button_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick photo.
        /// </summary>
        public static string StreamPage_Button_Library {
            get {
                return ResourceManager.GetString("StreamPage_Button_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string StreamPage_Button_More {
            get {
                return ResourceManager.GetString("StreamPage_Button_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string StreamPage_Button_Refresh {
            get {
                return ResourceManager.GetString("StreamPage_Button_Refresh", resourceCulture);
            }
        }
    }
}
